joy_node:
  # See documentation https://docs.ros.org/en/humble/p/joy/__README.html#parameters
  ros__parameters:
    device_id: 0
    device_name: ""
    deadzone: 0.05
    autorepeat_rate: 20.0
    sticky_buttons: false
    coalesce_interval_ms: 1


# teleop_node:
#   ros__parameters:
#     axis_linear:  # Left thumb stick vertical
#       x: 1
#     scale_linear:
#       x: 0.5
#     scale_linear_turbo:
#       x: 1.0
#     axis_angular:  # Left thumb stick horizontal
#       yaw: 0
#     scale_angular:
#       yaw: 0.5
#     scale_angular_turbo:
#       yaw: 1.0
#     gripper_topic: "/go"
#     require_enable_button: true
#     enable_button: 6  # Left shoulder button
#     enable_turbo_button: 7  # Right shoulder button


joystick_operator_node:
    # For button numbers: See documentation for "game_controller_node": https://docs.ros.org/en/humble/p/joy/__README.html#ros-2-driver-for-generic-joysticks-and-game-controllers
    # NOTE: The button numbers for "joy_node" (also supplied by the joy package) seem unpredictable.
    # Documentation for other parameters are in joystick_teleop_node.hpp
    ros__parameters:
        deadman_button: 9
        servo_twist_topic: "/servo_node/delta_twist_cmds"
        gripper_topic: "/ppm/gripper/ch0/command"
        joy_topic: "/arm/joy"
        # TODO: Make base_frame_id and wrist_frame_id actually change the strings sent.
        base_frame_id: base_link
        wrist_frame_id: wrist_link
        slow_button: 10
        slow_modifier: 0.1
        axis_x:
          joystick_axis: 1
          invert: 1
        axis_y:
          joystick_axis: 0
          invert: 1
        axis_z:
          joystick_axis: 3
          invert: 0
        gripper:
          speed: 50.0
          min: 0.0
          max: 180.0
          close_button: 0
          open_button: 1
        wrist_buttons:
          pitch_up: 11
          pitch_down: 12
          roll_left: 13
          roll_right: 14


gripper_ppm_node:
  ros__parameters:
    babbler_prefix: /arm/babbler
    ppm_prefix: /arm/ppm
    name: gripper
    src_addr: 99
    babbler_servo_id: 1