name: Assert version is incremented

on:
  pull_request:
    branches:
      - main

jobs:
  check-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout pr branch
        uses: actions/checkout@v4
        with:
          path: ./pr

      - name: Checkout base branch
        uses: actions/checkout@v4
        with:
          path: ./base
          ref: main

      - name: Extract version numbers
        working-directory: .
        id: extract-versions
        run: |
          echo "PR_PKG_VERSION=$(xml_grep --text_only 'package/version' pr/package.xml)" >> "$GITHUB_OUTPUT"
          echo "BASE_PKG_VERSION=$(xml_grep --text_only 'package/version' base/package.xml)" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Compare semantic versions
        uses: aleoyakas/check-semver-increased-action@v1
        id: check-version
        with:
          current-version: ${{ steps.extract-versions.outputs.PR_PKG_VERSION }}
          previous-version: ${{ steps.extract-versions.outputs.BASE_PKG_VERSION }}

      - name: Validated?
        if: steps.action.outputs.is-version-increased != 'true'
        run: echo "::error::Version is not incremented, $PR_PKG_VERSION is not greater than $BASE_PKG_VERSION"
        env:
          PR_PKG_VERSION: ${{ steps.extract-versions.outputs.PR_PKG_VERSION }}
          BASE_PKG_VERSION: ${{ steps.extract-versions.outputs.BASE_PKG_VERSION }}